<h1 style="text-align: center; color: #000000;">
    <strong>Funciones</strong>
</h1>

# Octave

## PseudoInversa

In [1]:
function x = pesudoinv_newton_schultz_2(A, b)

    % Dimension A = (filas, columnas) %
    [m, n] = size(A);

    % Tolerancia %
    tol = 10^-8;

    % Error %
    err = tol + 1;

    % Valor Inicial X0 %
    x0 = (1 / norm(A)^2) * A';

    % Vector Resultante %
    xk = x0;

    % Iteracion para hallar la Pseudoinversa %
    while (tol < err)
        xk = xk * (2* eye(m) - A * xk);
        err = norm(A * xk * A - A, 'fro');
    end

    % Pseudoinversa %
    Ap = xk;

    % Aproximar la Solucion %
    x = Ap * b;

    % Error %
    error = norm(A * x - b);
  
end

% A = [4, 2; -5, 3; 0, 1; 4, 1; 3, 0]
% b = [1; -1; 2; -2; 3]

% x = pesudoinv_newton_schultz_2(A, b)

In [2]:
A = [4, 2; -5, 3; 0, 1; 4, 1; 3, 0]
b = [1; -1; 2; -2; 3]

x = pesudoinv_newton_schultz_2(A, b)

A =

   4   2
  -5   3
   0   1
   4   1
   3   0

b =

   1
  -1
   2
  -2
   3

x =

   0.149847
  -0.036697



## Trazadores Cúbicos

In [5]:
function x = thomas(A, d)
    [m, n] = size(A);

    if (m != n)
        display("La matriz no es cuadrada.")
        x = 0;
        return;
    end

    if( det(A) == 0)
        display("La matriz no es invertible.")
        x = 0;
        return;
    end

    if (isbanded(A,1,1) == 0)
        display("La matriz no es tridiagonal.")
         x = 0;
        return;
    end

    a = [0];
    a = [a diag(A, -1)'];

    b = [diag(A)'];

    c = [diag(A, 1)'];
    c = [c 0];

    d = d';

    w(1) = b(1);
    g(1) = d(1) / w(1);

    for (i = 2 : n)
        w(i) = b(i) - a(i) * c(i - 1) / w(i - 1); 
        g(i) = (d(i) - a(i) * g(i - 1)) / w(i);
    end

    x(n) = g(n); 

    for (i = n - 1 : -1 : 1)
        x(i) = g(i) - c(i)*x(i+1)/w(i);
    end
    
end

% A = [7, 5, 0, 0; 2, -8, 1, 0; 0, 6, 4, 3; 0, 0, 9, 8]
% d = [6; 5; 7; 8]

    % a = [0; -1; 2; 1]
    % b = [1; 4; 1; 2]
    % c = [2; 3; 1; 0]
    % d = [1; 1; 1; 1]

    % a = [0, 1, 2, 1, 2, 1]  
    % b = [5, 3, 4, 2, 3, 2]  
    % c = [4, 1, 1, 1, 2, 0]
    % d = [13, 10, 20, 16, 35, 17]

    % a = [0 2 6 9];
    % b = [7 -8 4 8];
    % c = [5 1 3 0];
    % d = [6 5 7 8];

% x = thomas(A, d)

In [7]:
function S = trazadores_cubicos(vx, vy)
    % Delcaracion: Variable Literal 'x' %
    syms x;

    % Calculo: Dimension de los Vectores %
    len_vx = length(vx);
    len_vy = length(vy);   
    
    % Verificacion: Ambos Largos deben Coincidir %
    if (len_vx !=  len_vy)
        dislpay("Los dos vectores deben contener el mismo numero de elementos.");
    end

    % Asignacion: 'n' como variable de limite %
    n = len_vx;
    n

    % --------------------- %
    % Paso 1: Calcular 'hi' %
    % --------------------- %

    hi = zeros(1, (n - 1));

    %for (i = 1 : (len_vx -1))
        %h(i) = x(i+1) - x(i);
    %end

    hi = vx(2 : n) - vx(1 : (n - 1));

    hi

    % --------------------- %
    % Paso 2: Calcular 'ui' %
    % --------------------- %
    ui = zeros(1, n - 2);

    for (i = 1 : (n - 2))
        %frac_1 = ((vy(i + 2) - vy(i + 1)) / hi(i + 1));
        %frac_2 = ((vy(i + 1) - vy(i)) / hi(i));
        %ui_t = 6 * (frac_1 - frac_2);
        ui_t = 6 * (((vy(i + 2) - vy(i + 1)) / hi(i + 1)) - ((vy(i + 1) - vy(i)) / hi(i)));
        ui(i) = ui_t;
    end
    
    ui

    % ---------------------------------- %
    % Paso 3: Construir Matriz A 'mat_A' %
    % ---------------------------------- %
    dim_A = n - 2;

    A = zeros(dim_A, dim_A);
    for(i = 1 : dim_A)
        for (j = 1 : dim_A)
            if (i == j)
                A(i, j) = 2 * (hi(i) + hi(i + 1));
            end
        end
    end

    diag_sup = diag(A, 1);
    for (i = 1 : length(diag_sup))
        diag_sup(i) = hi(i + 1);
    end 

    diag_inf = diag(A, -1);
    for (i = 1 : length(diag_inf))
        diag_inf(i) = hi(i + 1);
    end 

    mat_A = diag(diag_sup, 1) + diag(diag(A)) + diag(diag_inf, -1);
    mat_A
    
    % ------------------------------------------------------------ %
    % Paso 4: Solucion (mat_A * m = ui) con Metodo de Thomas = 'M' %
    % ------------------------------------------------------------ %
    M = thomas(mat_A, ui');
    M

    % Mi(0) = M(n) = 0  => Frontera Natual o Libre%
    M = [0 M];
    M = [M 0];
    M

    % ------------------------------------------------- %
    % Paso 5: Calculo Constantes 'ai', 'bi', 'ci', 'di' %
    % ------------------------------------------------- %
    ai = [];
    bi = [];
    ci = [];
    di = [];

    for (i = 1 : (n - 1))
        ai(i) = (M(i + 1) - M(i)) / (6 * hi(i));
        bi(i) = M(i) / 2;
        ci(i) = ((vy(i + 1) - vy(i)) / (hi(i))) - ((hi(i) / 6) * (M(i + 1) + (2 * M(i))));
        di(i) = vy(i);
    end

    ai
    bi
    ci
    di

    % ------------------------------- %
    %     Paso 6: Calcular 'si(x)'    %
    %               +                 %
    % Paso 7: Agregarlo al Vector 'S' %
    % ------------------------------- %
    S = [];

    for (i = 1 : (n - 1))
        si = (ai(i) * (x - vx(i))^3) + (bi(i) * (x - vx(i))^2) + (ci(i) * (x - vx(i))) + (di(i));
        si_simp = simplify(si)
        S = [S si_simp];
    end;

    S

    %for (i = 1: length(S))
    %    ezplot(S(i))
    %end


end

% vx = [1, 1.05, 1.07, 1.1]
% vy = [2.718282, 3.286299, 3.527609, 3.905416]

% S = trazadores_cubicos(vx, vy)

In [8]:
pkg load symbolic
vx = [1, 1.05, 1.07, 1.1]
vy = [2.718282, 3.286299, 3.527609, 3.905416]

% warning('off', 'all')
S = trazadores_cubicos(vx, vy)

vx =

   1.0000   1.0500   1.0700   1.1000

vy =

   2.7183   3.2863   3.5276   3.9054

n =  4
hi =

   0.050000   0.020000   0.030000

ui =

   4.2310   3.1684

mat_A =

   0.140000   0.020000
   0.020000   0.100000

M =

   26.451   26.394

M =

    0.00000   26.45059   26.39388    0.00000

ai =

    88.16863    -0.47255  -146.63268

bi =

    0.00000   13.22529   13.19694

ci =

   11.140   11.801   12.330

di =

   2.7183   3.2863   3.5276

    double_to_sym_heuristic at line 50 column 7
    sym at line 379 column 13
    mtimes at line 63 column 5
    trazadores_cubicos at line 113 column 12
    double_to_sym_heuristic at line 50 column 7
    sym at line 379 column 13
    mtimes at line 63 column 5
    trazadores_cubicos at line 113 column 12
    double_to_sym_heuristic at line 50 column 7
    sym at line 379 column 13
    plus at line 61 column 5
    trazadores_cubicos at line 113 column 12
si_simp = (sym)

    ⎛                              3           ⎞
  π⋅⎝45359776⋅x + 3590069

# Python